"""first

Revision ID: b386a4c76ded
Revises: 
Create Date: 2022-09-28 14:00:04.485549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b386a4c76ded'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.REAL(), nullable=False),
    sa.Column('cur_name', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency',
    sa.Column('cur_id', sa.Integer(), nullable=False),
    sa.Column('cur_name', sa.String(length=3), nullable=False),
    sa.Column('relative_cost', sa.REAL(), nullable=False),
    sa.Column('available_amount', sa.REAL(), nullable=False),
    sa.Column('cur_date', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('cur_id')
    )
    op.create_table('deposite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opening_date', sa.String(length=10), nullable=False),
    sa.Column('closing_date', sa.String(length=10), nullable=False),
    sa.Column('balance', sa.REAL(), nullable=False),
    sa.Column('interest_rate', sa.Integer(), nullable=False),
    sa.Column('storage_conditions', sa.Integer(), nullable=False),
    sa.Column('storage_cur', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('spent_amount', sa.REAL(), nullable=False),
    sa.Column('datetime', sa.String(length=10), nullable=False),
    sa.Column('gain_amount', sa.REAL(), nullable=False),
    sa.Column('commission', sa.REAL(), nullable=False),
    sa.Column('account_from', sa.Integer(), nullable=False),
    sa.Column('account_to', sa.Integer(), nullable=False),
    sa.Column('cur_to', sa.Integer(), nullable=False),
    sa.Column('cur_from', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('user')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cur_name', sa.String(length=3), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('login', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('rating')
    op.drop_table('operation')
    op.drop_table('deposite')
    op.drop_table('currency')
    op.drop_table('account')
    # ### end Alembic commands ###
