"""second

Revision ID: 073e5e5fe5a2
Revises: f22a54329557
Create Date: 2022-10-16 19:46:17.928964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073e5e5fe5a2'
down_revision = 'f22a54329557'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
