# Generated by Django 4.1.2 on 2022-10-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffee_night', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_route', models.IntegerField()),
                ('text', models.TextField(max_length=500)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
