# Generated by Django 4.1.2 on 2022-10-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_route', models.IntegerField()),
                ('event_admin', models.IntegerField()),
                ('approved_users', models.JSONField()),
                ('pending_users', models.JSONField()),
                ('start_data', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.IntegerField()),
                ('stop_point', models.JSONField()),
                ('destination_point', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('loc', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('route_type', models.CharField(choices=[('HIKING', 'Hiking'), ('MOUNTAIN_CLIMBING', 'Mountain climbing'), ('SKIING', 'Skiing'), ('SNOWBOARDING', 'Snowboarding'), ('CAMPING', 'Camping'), ('FISHING', 'Fishing'), ('BIKING', 'Biking'), ('HUNTING', 'Hunting'), ('PHOTOGRAPHY', 'Photography'), ('OTHER', 'Other')], default='HIKING', max_length=50)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
