"""the_right_one

Revision ID: 0da34ed91639
Revises: 
Create Date: 2022-10-12 19:58:18.635919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da34ed91639'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.String(length=50), nullable=False),
    sa.Column('cur_name', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('cur_id', sa.Integer(), nullable=False),
    sa.Column('cur_name', sa.String(length=3), nullable=False),
    sa.Column('relative_cost', sa.String(length=10), nullable=False),
    sa.Column('available_amount', sa.String(length=10), nullable=False),
    sa.Column('cur_date', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('cur_id')
    )
    op.create_table('deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opening_date', sa.String(length=10), nullable=False),
    sa.Column('closing_date', sa.String(length=10), nullable=False),
    sa.Column('balance', sa.String(length=10), nullable=False),
    sa.Column('interest_rate', sa.Integer(), nullable=False),
    sa.Column('storage_conditions', sa.Integer(), nullable=False),
    sa.Column('storage_cur', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations',
    sa.Column('operation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spent_amount', sa.String(length=10), nullable=False),
    sa.Column('datetime', sa.String(length=10), nullable=False),
    sa.Column('gain_amount', sa.String(length=10), nullable=False),
    sa.Column('commission', sa.Integer(), nullable=False),
    sa.Column('account_from', sa.Integer(), nullable=False),
    sa.Column('account_to', sa.Integer(), nullable=False),
    sa.Column('cur_to', sa.String(length=3), nullable=False),
    sa.Column('cur_from', sa.String(length=3), nullable=False),
    sa.Column('operation_type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('operation_id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cur_name', sa.String(length=3), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('login', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('ratings')
    op.drop_table('operations')
    op.drop_table('deposits')
    op.drop_table('currencies')
    op.drop_table('accounts')
    # ### end Alembic commands ###
